[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NODE_VERSION = "20"
  NEXT_PUBLIC_SUPABASE_URL = "https://krvjhuvgjywhhxycirub.supabase.co"
  NEXT_PUBLIC_SUPABASE_ANON_KEY = "sb_publishable_UWpeWYwiAuHjtWoLKWgkaA_xiGbG_Qr"

[[headers]]
  for = "/sw.js"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/manifest.json"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"
